name: Snapshot Build

on:
  workflow_dispatch:
  schedule:
  - cron: "30 2 * * 6"

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%yd%ja')"

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Compile roblox-ts
        run: |
          npm run compile

      - name: Build model
        run: |
          npm run build

      - name: Bundle modules
        run: |
          remodel run ci/bundle-prod.lua public/snapshot.lua ${{ steps.date.outputs.date }}
          remodel run ci/bundle-debug.lua public/snapshot.debug.lua ${{ steps.date.outputs.date }}-debug

      - name: Commit weekly snapshot
        uses: EndBug/add-and-commit@v8.0.2
        with:
          default_author: "github_actions"
          add: "['public/snapshot.lua', 'public/snapshot.debug.lua']"
          message: 🔥 Weekly snapshot ${{ steps.date.outputs.date }}
